### PR TITLE
Support FIDO MDS v3

### LINKED ISSUE #7: Support FIDO metadata service version 3 for attestations
Copied from: https://github.com/cedarcode/webauthn-ruby/issues/375

From https://developers.yubico.com/WebAuthn/Concepts/Securing_WebAuthn_with_Attestation.html#_recommendations 

> You can find the root certificates used to sign attestations on manufacturer websites (Yubico’s is [here](https://developers.yubico.com/U2F/yubico-u2f-ca-certs.txt)) or in the [FIDO metadata service version 3](https://fidoalliance.org/metadata/).

> The FIDO Alliance Metadata Service (MDS) is a centralized repository of the Metadata Statement that is used by the relying parties to validate authenticator attestation and prove the genuineness of the device model. MDS also provides information about certification status of the authenticators, and found security issues. Organizations deploying FIDO Authentication are able to use this information to select specific certification levels as required for compliance, and work through the security notifications to ensure effective incident response.

From https://fidoalliance.org/metadata/

### PR DESCRIPTION
**Pull request by santiagorodriguez96**
## Summary

Attempts to fix #7. Following [this comment](https://github.com/bdewater/fido_metadata/issues/7#issuecomment-1281024353), dropped v2 in favor of v3.

Overall, the changes are:
- Now all the metadata comes as one BLOB file – there's no need to download multiple TOC files anymore. The `entries` of the BLOB file now contain a `metadataStatement` key which contains the metadata object.
- A token is no longer needed to access to MDS.
- Updated root certificate - downloaded from https://mds.fidoalliance.org/.
- Changes to Metadata Statement:
    - `authenticationAlgorithms` and `publicKeyAlgAndEncodings` replaced `authenticationAlgorithm` and `publicKeyAlgAndEncoding` respectively.
    - `assertionScheme`, `operatingEnv`, `isSecondFactorOnly` fields were removed.
    - `schema` and `authenticatorGetInfo` fields were added.
    - `attestationTypes`, `userVerificationDetails`, `keyProtection`, `matcherProtection`, `attachmentHint`, `tcDisplay` numerical fields became string.

## References

- https://fidoalliance.org/metadata/
- https://fidoalliance.org/specs/mds/fido-metadata-service-v3.0-ps-20210518.html
- https://fidoalliance.org/specs/mds/fido-metadata-statement-v3.0-ps-20210518.html
- https://medium.com/webauthnworks/webauthn-fido2-whats-new-in-mds3-migrating-from-mds2-to-mds3-a271d82cb774

### CODE REVIEW

**Comment by bdewater** [comment]
Thank you so much! I'll try to get to this and the other open PRs by end of week.

**Comment by bdewater** [comment]
Thanks again and sorry for the delay! I can cut an RC release for https://github.com/cedarcode/webauthn-ruby/pull/407 if that helps.

**Comment by santiagorodriguez96** [comment]
That would be great! Thank you! ❤️

**Comment by santiagorodriguez96** [comment]
> Thanks again and sorry for the delay! I can cut an RC release for [cedarcode/webauthn-ruby#407](https://github.com/cedarcode/webauthn-ruby/pull/407) if that helps.

@bdewater Hi! Hope you’re doing well! Just bumping this up in case it fell through the cracks :)

**Pull request merged**
